const themeButton = document.querySelector("#theme");
themeButton.addEventListener("click", () =>
  document.documentElement.toggleAttribute("data-dark"),
);

const original = new Map();
document.querySelectorAll("body *").forEach((element) => {
  if (element.children.length === 0) original.set(element, element.textContent);
});

const english = {
  ".nav nav a": ["About", "Experience", "Projects", "Contact"],
  ".brand": ["Wang Kai"],
  ".hero .serif": ["Hello, I’m"],
  ".hero h1": ["Wang Kai"],
  ".hero h2": ["Large Model Operations Specialist @ Kuaishou"],
  ".hero .meta": ["AI NATIVE PRACTITIONER · E-COMMERCE & COMMERCIALIZATION"],
  ".hero .intro": [
    "I map AI capabilities across end-to-end business workflows, break down problems, and ship practical solutions—from intelligent governance to Agents, Workflows, Skills, and scalable model training.",
  ],
  ".hero .button": ["View experience ↓", "Explore projects →"],
  ".heading h2": [
    "About",
    "Professional Skills",
    "Strengths",
    "Education",
    "Experience",
    "Selected Projects",
  ],
  ".about .quote": [
    "I believe AI creates value not in demos, but in measurable business outcomes.",
  ],
  ".about > div > p": [
    "I graduated with a bachelor’s degree in 2022 and have worked on AI initiatives at ByteDance and Kuaishou—from automated risk review to the scaled adoption of Agents, Workflows, Skills, and model training.",
  ],
  ".profile-facts small": ["Born", "Location", "Degree", "Phone", "Email"],
  ".profile-facts strong": ["2001.03", "Chengdu, Sichuan", "Bachelor’s"],
  ".pills span": [
    "Agent",
    "Workflow",
    "Skill",
    "Model Training",
    "Intelligent Governance",
    "Data Analytics",
    "Agent",
    "Skill",
    "Workflow",
    "Model Training",
    "AI Evaluation",
    "Automated Review",
    "Risk Strategy",
    "Model-driven Rules",
    "Data Analytics",
  ],
  ".skill-rows h3": [
    "AI / Agent",
    "Code / Analytics",
    "Platforms / Tools",
    "Domain Expertise",
  ],
  ".skill-rows p": [
    "Prompt engineering, Agent workflow design, Workflow orchestration, Few-shot tuning, model capability evaluation, and RAG applications.",
    "Python, SQL, Java (AI-assisted / vibe coding), data analysis (batch cleaning and multidimensional statistical analysis for standardized datasets), and HTTP API integration (authentication, pagination, exception handling, and response parsing).",
    "Low-code workflow platforms, Skill framework development, automated-review / governance strategy platforms, and internal tool deployment.",
    "Content risk control, e-commerce risk control, automated-review strategy, project management (PMO), team development, and methodology building.",
  ],
  ".advantages b": [
    "AI Agent Delivery",
    "AI-native Tooling",
    "Content & E-commerce Risk",
    "Program Leadership & Talent Development",
  ],
  ".advantages p": [
    "Led and contributed to multiple e-commerce automated-review projects from 0→1. Independently designed Agent chains, prompts, and Workflows, turning complex business SOPs into scalable model-executable capabilities.",
    "Proficient in vibe coding with Python, SQL, and Java. Independently built internal AI tools used by 200+ employees and helped teams adopt AI-native ways of working.",
    "Built multiple e-commerce risk-control pipelines from 0→1 across content, products, prohibited goods, and red-line scenarios. Strong at combining policy interpretation, risk sensing, and automated review for high-precision recall and efficiency.",
    "Experienced in PMO management, resource coordination, and delivery cadence. Trained 200+ prompt engineers and codified reusable methods and training materials.",
  ],
  ".education h3": [
    "Zhejiang Gongshang University Hangzhou College of Commerce",
  ],
  ".education div p": ["Financial Management (Bachelor’s)"],
  ".education > p": [
    "Core coursework: Probability & Mathematical Statistics, Advanced Mathematics, Linear Algebra, Statistics, Programming Fundamentals & Data Processing, and Financial Management.",
  ],
  ".job h3": [
    "Sichuan Kuaishou — Large Model Training",
    "ByteDance — E-commerce Automated Review",
  ],
  ".job h4": [
    "Large Model Operations Specialist",
    "Counterfeit Automated-Review Operations Specialist",
  ],
  ".job .meta": [
    "Large Model Training · E-commerce and Commercialization",
    "China Content Quality & Data Services Platform (Content Risk Quality)",
  ],
  ".job > div:last-child > p:not(.meta)": [
    "Drive large-model adoption in e-commerce and commercialization. Led 0→1 platform capability mapping, Agent tools, PE training, Agent-chain development, Workflows, and internal AI tooling for merchant onboarding, prohibited-content scenarios, and more.",
    "Owned products, tools, Agents, and special initiatives for counterfeit e-commerce review. Delivered reusable Agents for selling-intent detection, product matching, and automated rule creation, together with training materials and operating methods.",
  ],
  ".job li": [
    "Talent development: As a large-model training mentor, delivered two sessions to 200+ e-commerce and commercialization professionals and developed a cohort of 11 model trainers.",
    "Skill engineering: Improved client-development operations by 30%+, reached 264 users, and achieved 1,200+ total installations.",
    "Risk coverage through automated-review models: team coverage increased from 0→74.1% (personal contribution +16.55%); enabled a reduction of 162 roles (personal contribution: 38, or 23.5%).",
    "Built the new-hire training system: completed 5 cohorts and trained 150+ new hires while coordinating 3 PEs and a 5-person annotation team; codified reusable curricula and assignment standards.",
    "Received 5 team awards rated A or above and an M+ 360 performance rating (exceeded expectations).",
  ],
  ".case h3": [
    "Intelligent Merchant Onboarding Review",
    "Skill Engineering · Client Development Digital Human",
    "Product Matching Agent (Foundation Capability)",
    "Intelligent Rule Creation · Weight-Loss Initiative",
  ],
  ".case header small": [
    "Kuaishou · Lead PMO · 0→1",
    "Kuaishou · Core Developer · 0→1",
    "ByteDance · Owner · 0→1",
    "ByteDance · Core Developer",
  ],
  ".case-bg": [
    "Background: Merchant onboarding was scaling rapidly while qualification review remained highly dependent on manual work. Store-opening time lagged far behind the industry’s hourly benchmark, creating high labor cost and an efficiency bottleneck. The target was a 70% automated-review rate.",
    "Background: Compliance reporting is critical to client-development workflows. Staff had to process multiple reports one by one on PC, and query costs increased with volume, creating an urgent need for a digital-human solution.",
    "Background: Counterfeit governance involved many livestream-selling cases without explicit product codes. Traditional code extraction failed, leaving products unmatched and risk blind spots unresolved. A reusable foundation-level product-matching capability was required.",
    "Background: False weight-loss claims persisted as creator tactics changed. Manual rule creation was experience-dependent, slow, and limited in coverage, requiring more automated and scalable risk discovery and interception.",
  ],
  ".case li": [
    "As lead PMO, owned target decomposition, resource coordination, and delivery cadence. Combined manual-review SOPs with governance rules, prioritized review stages by model feasibility and ROI, set the roadmap, authored the workflow-platform BRD, and drove the foundation platform from 0→1.",
    "Built AI recognition from high-ROI stages: subjective decisions were handled through model prompts, while data transformation and cleaning ran in Workflow Python nodes. Codified the approach and developed 5 PEs to scale automated-review capabilities.",
    "Addressed coding gaps across PE and governance teams by independently vibe-coding the internal ‘Intelligent Application Suite’—including code generation, SQL generation, feature authoring, and assistants. Standardized feature authoring for 90+ internal users and 1,500+ calls; reduced PRD/R&D alignment cycles by 3+ and shortened development by more than one day.",
    "Results: automated-review coverage 0→71% (Q1 target 40%, achieved 48%; Q2 target 65%, achieved 71%, both above target); 84 models launched with 98.41% average online accuracy, 0.97% false-positive rate, and 0.62% miss rate; per-case AHT 219s→154s (−29.7%), saving 11 roles.",
    "Solved workflow disconnects by developing batch-report lookup and report-creation Skills and integrating them into the client-development digital human, enabling mobile reporting and shortening development from two weeks to one week.",
    "Improved evaluation by converting delivery and product requirements into an Evaluation Skill. Achieved 90%+ Skill evaluation accuracy and integrated the capability into the development platform.",
    "Results: 1,220+ Skill installations, 264 users reached, 700+ calls, and 30%+ improvement in client-development reporting efficiency.",
    "Built the overall Agent framework and link-matching prompts from 0→1. Decomposed creator fraud patterns into three parallel paths—link, blacklisted term, and style—then merged results to output link IDs and complete product information.",
    "Reworked matching from ‘extract product code from speech’ to using the large model to encode livestream links, verify price, and assess category match—solving missing-code scenarios and creating a reusable foundation capability for upper-layer risk controls.",
    "Results: product-matching accuracy remained above 90% in stable production use, resolving missing-link and incorrect-match issues.",
    "Explored automated risk discovery and interception: aligned governance and product teams on rule-control risks, combined CPO negative-feedback data with creator fraud intent, generated intent rules with models, and drove rule deployment and communication.",
    "Built the data-analysis pipeline by coordinating rule-control decomposition, analyzing negative-feedback cases, constructing the Agent chain, and designing rule exemptions and task decomposition for high-precision automated rejection.",
    "Codified resource-monitoring practice with algorithm teams across rejection volume and QPS, diagnosed plugin-resource and ASR transcription issues, stabilized production rollout, and shared the approach to support productization.",
    "Results: deployed 2 rules for false weight-loss promotion; CPO ticket recall increased from 71% to a stable 80%+; ASR transcription-error share fell from 12.5% to 4.8%.",
  ],
  ".contact > small": ["LET’S TALK"],
  ".contact h2": ["Let’s build something meaningful."],
  ".contact > p:not(.cv-note)": [
    "If you care about bringing AI into real business workflows, I’d love to connect.",
  ],
  ".contact-card span": ["Send email →", "Call →"],
  ".cv-note": ["CV file coming soon · Contact details updated"],
  footer: ["© 2026 Wang Kai · Personal Homepage"],
};

const traditionalPairs = [
  "后後",
  "发發",
  "历歷",
  "业業",
  "专專",
  "与與",
  "为為",
  "个個",
  "东東",
  "丝絲",
  "两兩",
  "严嚴",
  "临臨",
  "义義",
  "举舉",
  "习習",
  "书書",
  "买買",
  "乱亂",
  "争爭",
  "于於",
  "亚亞",
  "产產",
  "亩畝",
  "亲親",
  "亿億",
  "仅僅",
  "从從",
  "仑侖",
  "仓倉",
  "仪儀",
  "们們",
  "价價",
  "众眾",
  "优優",
  "会會",
  "伞傘",
  "伟偉",
  "传傳",
  "伤傷",
  "伦倫",
  "伪偽",
  "体體",
  "余餘",
  "佣傭",
  "侠俠",
  "侣侶",
  "侥僥",
  "侧側",
  "侦偵",
  "侨僑",
  "俩倆",
  "俭儉",
  "债債",
  "倾傾",
  "偿償",
  "储儲",
  "儿兒",
  "兑兌",
  "党黨",
  "兰蘭",
  "关關",
  "兴興",
  "养養",
  "兽獸",
  "内內",
  "冈岡",
  "册冊",
  "写寫",
  "军軍",
  "农農",
  "冲沖",
  "决決",
  "况況",
  "冻凍",
  "净淨",
  "减減",
  "几幾",
  "凤鳳",
  "凭憑",
  "凯凱",
  "击擊",
  "划劃",
  "刘劉",
  "则則",
  "刚剛",
  "创創",
  "删刪",
  "别別",
  "刽劊",
  "剂劑",
  "剑劍",
  "剧劇",
  "劝勸",
  "办辦",
  "务務",
  "动動",
  "励勵",
  "劲勁",
  "劳勞",
  "势勢",
  "勋勳",
  "区區",
  "医醫",
  "华華",
  "协協",
  "单單",
  "卖賣",
  "卢盧",
  "卫衛",
  "却卻",
  "厂廠",
  "厅廳",
  "县縣",
  "参參",
  "双雙",
  "变變",
  "叙敘",
  "叶葉",
  "号號",
  "叹嘆",
  "吓嚇",
  "听聽",
  "启啟",
  "吴吳",
  "员員",
  "呛嗆",
  "呜嗚",
  "咏詠",
  "咸鹹",
  "响響",
  "哑啞",
  "哗嘩",
  "唤喚",
  "啸嘯",
  "喷噴",
  "团團",
  "园園",
  "围圍",
  "图圖",
  "圆圓",
  "圣聖",
  "场場",
  "坏壞",
  "块塊",
  "坚堅",
  "坛壇",
  "坝壩",
  "壮壯",
  "声聲",
  "壳殼",
  "处處",
  "备備",
  "复復",
  "头頭",
  "夹夾",
  "夺奪",
  "奋奮",
  "奖獎",
  "妇婦",
  "妈媽",
  "学學",
  "宁寧",
  "宝寶",
  "实實",
  "审審",
  "宫宮",
  "宽寬",
  "对對",
  "导導",
  "将將",
  "层層",
  "届屆",
  "属屬",
  "岗崗",
  "岛島",
  "岭嶺",
  "岳嶽",
  "岁歲",
  "帅帥",
  "师師",
  "帐帳",
  "带帶",
  "帮幫",
  "干幹",
  "并並",
  "广廣",
  "庄莊",
  "庆慶",
  "库庫",
  "应應",
  "庙廟",
  "废廢",
  "开開",
  "异異",
  "弃棄",
  "张張",
  "弥彌",
  "强強",
  "归歸",
  "当當",
  "录錄",
  "彻徹",
  "径徑",
  "忆憶",
  "忧憂",
  "态態",
  "怀懷",
  "总總",
  "恶惡",
  "恼惱",
  "惊驚",
  "惨慘",
  "惯慣",
  "愿願",
  "戏戲",
  "户戶",
  "执執",
  "扩擴",
  "扫掃",
  "扬揚",
  "扰擾",
  "抚撫",
  "抛拋",
  "抢搶",
  "护護",
  "报報",
  "担擔",
  "拟擬",
  "拥擁",
  "择擇",
  "挂掛",
  "挡擋",
  "据據",
  "损損",
  "换換",
  "掩掩",
  "携攜",
  "摄攝",
  "摆擺",
  "摇搖",
  "撑撐",
  "数數",
  "断斷",
  "无無",
  "旧舊",
  "时時",
  "显顯",
  "晋晉",
  "术術",
  "机機",
  "杀殺",
  "权權",
  "条條",
  "来來",
  "杨楊",
  "极極",
  "构構",
  "标標",
  "样樣",
  "档檔",
  "桥橋",
  "检檢",
  "楼樓",
  "欢歡",
  "欧歐",
  "步步",
  "残殘",
  "毁毀",
  "毕畢",
  "气氣",
  "汇匯",
  "汉漢",
  "汤湯",
  "沟溝",
  "沪滬",
  "泪淚",
  "洁潔",
  "浅淺",
  "测測",
  "济濟",
  "浏瀏",
  "浑渾",
  "浓濃",
  "涌湧",
  "润潤",
  "涨漲",
  "涩澀",
  "渊淵",
  "渐漸",
  "温溫",
  "湾灣",
  "湿濕",
  "满滿",
  "滤濾",
  "灭滅",
  "灯燈",
  "灵靈",
  "灾災",
  "点點",
  "炼煉",
  "热熱",
  "爱愛",
  "爷爺",
  "牵牽",
  "状狀",
  "犹猶",
  "狱獄",
  "猎獵",
  "环環",
  "现現",
  "琐瑣",
  "电電",
  "画畫",
  "畅暢",
  "疗療",
  "监監",
  "盖蓋",
  "盘盤",
  "着著",
  "睁睜",
  "瞒瞞",
  "矿礦",
  "码碼",
  "砖磚",
  "础礎",
  "礼禮",
  "离離",
  "种種",
  "积積",
  "称稱",
  "稳穩",
  "穷窮",
  "窝窩",
  "竞競",
  "笔筆",
  "笼籠",
  "筑築",
  "简簡",
  "签簽",
  "类類",
  "粮糧",
  "紧緊",
  "纠糾",
  "红紅",
  "约約",
  "级級",
  "纪紀",
  "纯純",
  "纲綱",
  "纳納",
  "纵縱",
  "纷紛",
  "纸紙",
  "纹紋",
  "线線",
  "练練",
  "组組",
  "细細",
  "织織",
  "终終",
  "绍紹",
  "经經",
  "绑綁",
  "结結",
  "统統",
  "绳繩",
  "维維",
  "综綜",
  "绿綠",
  "编編",
  "缘緣",
  "缩縮",
  "网網",
  "罗羅",
  "罚罰",
  "职職",
  "联聯",
  "肃肅",
  "胜勝",
  "胶膠",
  "脑腦",
  "脸臉",
  "脱脫",
  "舰艦",
  "艺藝",
  "节節",
  "范範",
  "苏蘇",
  "获獲",
  "营營",
  "蓝藍",
  "虚虛",
  "虫蟲",
  "补補",
  "装裝",
  "观觀",
  "规規",
  "视視",
  "览覽",
  "觉覺",
  "触觸",
  "计計",
  "订訂",
  "认認",
  "讨討",
  "让讓",
  "训訓",
  "议議",
  "讯訊",
  "记記",
  "讲講",
  "许許",
  "论論",
  "设設",
  "访訪",
  "证證",
  "评評",
  "识識",
  "诉訴",
  "诊診",
  "词詞",
  "试試",
  "诗詩",
  "诚誠",
  "话話",
  "该該",
  "详詳",
  "语語",
  "误誤",
  "说說",
  "请請",
  "诸諸",
  "读讀",
  "调調",
  "谈談",
  "谋謀",
  "谓謂",
  "谢謝",
  "谨謹",
  "谱譜",
  "贝貝",
  "负負",
  "贡貢",
  "财財",
  "责責",
  "败敗",
  "货貨",
  "质質",
  "贩販",
  "贪貪",
  "贫貧",
  "购購",
  "贯貫",
  "贴貼",
  "贵貴",
  "贸貿",
  "费費",
  "贺賀",
  "资資",
  "赋賦",
  "赌賭",
  "赏賞",
  "赞讚",
  "赵趙",
  "赶趕",
  "趋趨",
  "跃躍",
  "车車",
  "轨軌",
  "转轉",
  "轮輪",
  "软軟",
  "轻輕",
  "载載",
  "较較",
  "辅輔",
  "辆輛",
  "辈輩",
  "边邊",
  "辽遼",
  "达達",
  "迁遷",
  "过過",
  "运運",
  "还還",
  "进進",
  "远遠",
  "违違",
  "连連",
  "迟遲",
  "适適",
  "选選",
  "递遞",
  "逻邏",
  "遗遺",
  "邮郵",
  "邻鄰",
  "郑鄭",
  "酝醞",
  "释釋",
  "里裡",
  "鉴鑒",
  "针針",
  "钉釘",
  "钓釣",
  "钟鐘",
  "钢鋼",
  "钱錢",
  "错錯",
  "链鏈",
  "销銷",
  "锁鎖",
  "锅鍋",
  "锻鍛",
  "镀鍍",
  "长長",
  "门門",
  "问問",
  "闲閒",
  "间間",
  "闯闖",
  "闻聞",
  "队隊",
  "阳陽",
  "阴陰",
  "阵陣",
  "阶階",
  "际際",
  "陆陸",
  "陈陳",
  "险險",
  "随隨",
  "隐隱",
  "难難",
  "雏雛",
  "杂雜",
  "静靜",
  "顶頂",
  "项項",
  "顺順",
  "须須",
  "预預",
  "领領",
  "颇頗",
  "频頻",
  "题題",
  "额額",
  "风風",
  "飞飛",
  "饭飯",
  "饮飲",
  "馆館",
  "验驗",
  "马馬",
  "驻駐",
  "驾駕",
  "骗騙",
  "骚騷",
  "鱼魚",
  "鲜鮮",
  "鸟鳥",
  "鸡雞",
  "鸣鳴",
  "麦麥",
  "黄黃",
  "齐齊",
  "齿齒",
  "龄齡",
  "龙龍",
];
const toTraditional = (value) => {
  const map = new Map(traditionalPairs.map((pair) => [...pair]));
  return [...value].map((char) => map.get(char) || char).join("");
};

function setTexts(selector, values) {
  document.querySelectorAll(selector).forEach((element, index) => {
    if (values[index] !== undefined) element.textContent = values[index];
  });
}

function setLocale(locale) {
  original.forEach((value, element) => {
    element.textContent = locale === "zh-TW" ? toTraditional(value) : value;
  });
  if (locale === "en")
    Object.entries(english).forEach(([selector, values]) =>
      setTexts(selector, values),
    );
  document.title =
    locale === "en"
      ? "Wang Kai · Large Model Operations Specialist"
      : locale === "zh-TW"
        ? "王凱 · 大模型運營專家"
        : "王凯 · 大模型运营专家";
  document.documentElement.lang = locale;
  document
    .querySelectorAll("[data-locale]")
    .forEach((button) =>
      button.classList.toggle("active", button.dataset.locale === locale),
    );
  localStorage.setItem("portfolio-locale", locale);
}

document.querySelectorAll("[data-locale]").forEach((button) =>
  button.addEventListener("click", () => {
    localStorage.setItem("portfolio-locale", button.dataset.locale);
    window.location.reload();
  }),
);
setLocale(localStorage.getItem("portfolio-locale") || "en");

const observer = new IntersectionObserver(
  (entries) =>
    entries.forEach(
      (entry) => entry.isIntersecting && entry.target.classList.add("visible"),
    ),
  { threshold: 0.12 },
);
document
  .querySelectorAll(".reveal")
  .forEach((element) => observer.observe(element));
window.addEventListener(
  "scroll",
  () =>
    document
      .querySelector(".nav")
      .classList.toggle("scrolled", window.scrollY > 40),
  { passive: true },
);
